use_frameworks!

platform :ios, '8.0'

target 'ZJKReflectUtil_Example' do
  pod 'ZJKReflectUtil', :path => '../'

  target 'ZJKReflectUtil_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
